-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE EXTENSION vector;

CREATE TABLE IF NOT EXISTS public."AUDIT"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    action text COLLATE pg_catalog."default",
    time_stamp date,
    CONSTRAINT "AUDIT_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HANDWRITING_SAMPLES"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    path text COLLATE pg_catalog."default" NOT NULL,
    student_no character varying(10) COLLATE pg_catalog."default" NOT NULL,
    embedding vector(256),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    model_version character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "IMAGES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."REFRESH_TOKENS"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    token text COLLATE pg_catalog."default" NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_revoked boolean NOT NULL DEFAULT false,
    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY (id),
    CONSTRAINT "REFRESH_TOKENS_token_key" UNIQUE (token)
);

CREATE TABLE IF NOT EXISTS public."STUDENTS"
(
    student_no character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "STUDENTS_pkey" PRIMARY KEY (student_no)
);

CREATE TABLE IF NOT EXISTS public."USER"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auto_increment PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."AUDIT"
    ADD CONSTRAINT forein_key_user_id FOREIGN KEY (user_id)
    REFERENCES public."USER" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."HANDWRITING_SAMPLES"
    ADD CONSTRAINT fk_student_id FOREIGN KEY (student_no)
    REFERENCES public."STUDENTS" (student_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_samples_student
    ON public."HANDWRITING_SAMPLES"(student_no);


ALTER TABLE IF EXISTS public."REFRESH_TOKENS"
    ADD CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id)
    REFERENCES public."USER" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
    
END;