-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE EXTENSION vector;


CREATE TABLE IF NOT EXISTS public."AUDIT"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    action text COLLATE pg_catalog."default",
    time_stamp date,
    CONSTRAINT "AUDIT_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."COURSES"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    code character varying(15) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "COURSES_pkey" PRIMARY KEY (id),
    CONSTRAINT "COURSES_code_key" UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public."IMAGES"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    path text COLLATE pg_catalog."default" NOT NULL,
    vector vector(10000) NOT NULL,
    student_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "IMAGES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."STUDENTS"
(
    student_no character varying(10) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "STUDENTS_pkey" PRIMARY KEY (student_no)
);

CREATE TABLE IF NOT EXISTS public."STUDENT_COURSE"
(
    student_id character varying(10) COLLATE pg_catalog."default" NOT NULL,
    course_code character varying(15) COLLATE pg_catalog."default" NOT NULL,
    current_year date NOT NULL,
    CONSTRAINT "STUDENT_COURSE_pkey" PRIMARY KEY (student_id, course_code)
);

CREATE TABLE IF NOT EXISTS public."USER"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    "Role" text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auto_increment PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."AUDIT"
    ADD CONSTRAINT forein_key_user_id FOREIGN KEY (user_id)
    REFERENCES public."USER" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."IMAGES"
    ADD CONSTRAINT fk_student_id FOREIGN KEY (student_id)
    REFERENCES public."STUDENTS" (student_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."STUDENT_COURSE"
    ADD CONSTRAINT fk_course_student FOREIGN KEY (course_code)
    REFERENCES public."COURSES" (code) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public."STUDENT_COURSE"
    ADD CONSTRAINT fk_student_course FOREIGN KEY (student_id)
    REFERENCES public."STUDENTS" (student_no) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

CREATE TABLE IF NOT EXISTS public."REFRESH_TOKENS"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    user_id integer NOT NULL,
    token text NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    is_revoked boolean NOT NULL DEFAULT false,
    CONSTRAINT "REFRESH_TOKENS_pkey" PRIMARY KEY (id),
    CONSTRAINT "REFRESH_TOKENS_token_key" UNIQUE (token),
    CONSTRAINT "fk_refresh_token_user" FOREIGN KEY (user_id)
        REFERENCES public."USER" (id)
        ON DELETE CASCADE
);

END;